### ISSUE TITLE
429 Error: Too many requests

### ISSUE THREAD

**Issue by BramR123** [asmitks/insta-graphql-scraper#12]
Hi!

The scraper worked great for a while, but all of a sudden, it doesn't seem to work anymore. I am running the scraper in Google Collabs and used to reset the factory runtime and such, but now it doesn't generate anymore output at all. I've tried it on multiple machines and multiple people tried it as well. Is there a fix for this or might the scraper be broken?

Thanks in advance!

**Comment by asmitks** [comment]
Hey 
Thanks for pointing this out. Turns out Instagram for some "odd" reason stopped accepting get requests without a user-agent values in the header of the request. Its working now.

Thanks
